[package]
name = "ab"
version = "0.1.0"
authors = ["Erdem Uysal <https://github.com/erdemuysal>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
